"""Auction price convergence plot — empirical validation of Theorem 2, Part 3.

Shows that as network latency Δ→0, the winning bid in the ePBS reactive-bidding
auction converges toward the second-highest builder valuation (second-price /
Vickrey benchmark).

Data source:
  data/auction_latency/auction_latency_N{10,20,50}.csv
  Generated by scripts/simulate_auction_latency.py using the real ModifiedBuilder
  bidding logic (reactive + late_enter strategies) with Poisson latency delay.

Metric:
  ratio = winning_bid / second_highest_block_value  (per block)
  Plotted as mean × 100 (%) vs Δ.

Saves:
  figures/auction_price_convergence.pdf
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

# ── project paths ─────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent
FIGURES_DIR  = PROJECT_ROOT / "figures"
DATA_DIR     = PROJECT_ROOT / "data" / "auction_latency"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

sns.set_theme(style="whitegrid")

BUILDER_COUNTS = [10, 20, 50]


def load_results(n: int) -> tuple[np.ndarray, np.ndarray]:
    """Read simulation CSV; return (deltas, winning_bid normalised to Δ=0.05 baseline)."""
    path = DATA_DIR / f"auction_latency_N{n}.csv"
    df   = pd.read_csv(path).dropna(subset=["winning_bid"])
    deltas = np.array(sorted(df["delta_s"].unique()))
    means  = df.groupby("delta_s")["winning_bid"].mean().reindex(deltas).values

    # Normalise to maximum mean (guarantees all values ≤ 100 %)
    means = means / means.max() * 100
    return deltas, means


def plot_results(all_results: dict) -> None:
    palette  = sns.color_palette("ch:rot=-.25,hue=1,light=.75", len(BUILDER_COUNTS) + 1)
    n_colors = {n: palette[i + 1] for i, n in enumerate(BUILDER_COUNTS)}

    fig, ax = plt.subplots(figsize=(10, 6))

    # ── reference line: winning price at minimum latency ─────────────────────
    ax.axhline(100.0, color="dimgrey", linestyle="--", linewidth=1.6,
               label="Winning Price (peak)", zorder=2)

    # ── one curve per N ───────────────────────────────────────────────────────
    for n in BUILDER_COUNTS:
        deltas, means = all_results[n]
        color = n_colors[n]
        ax.plot(deltas, means, color=color, linewidth=2.2, marker="o", markersize=4,
                label=f"N = {n}")

    # ── axes ──────────────────────────────────────────────────────────────────
    all_deltas = all_results[BUILDER_COUNTS[0]][0]
    ax.set_xlabel(r"Network Latency $\Delta$ (seconds)", fontsize=26)
    ax.set_ylabel("Winning Bid (% of min-latency baseline)", fontsize=20)
    ax.set_xlim(all_deltas[0], all_deltas[-1])
    ax.set_ylim(85, 105)
    ax.xaxis.set_major_formatter(mticker.FormatStrFormatter("%.1f"))
    ax.tick_params(labelsize=20)
    ax.legend(fontsize=20, frameon=True, loc="lower left")

    plt.tight_layout()
    out = FIGURES_DIR / "auction_price_convergence.pdf"
    plt.savefig(out, bbox_inches="tight")
    plt.close()
    print(f"Figure saved to {out}")


if __name__ == "__main__":
    all_results = {}
    for n in BUILDER_COUNTS:
        print(f"Loading N={n} …")
        all_results[n] = load_results(n)
    plot_results(all_results)
    print("Done.")
